version: "3.9"

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: "mood"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mypassword"
    networks:
      - app_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    networks:
      - app_network
    ports:
      - '3000:3000'
    depends_on:
      - api
    
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    networks:
      - app_network
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    env_file:
      - .env
    command: >
      sh -c "until nc -z postgres 5432; do echo 'Waiting for the database...'; sleep 1; done;
             pnpm turbo run db:push --filter=@repo/db && pnpm turbo run db:generate --filter=@repo/db &&
             pnpm dev --filter=api"
    
networks:
  app_network:
    external: false

volumes:
  postgres_data:
