version: "3.9"

services:
  postgres:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: "mood"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "mypassword"
    networks:
      - app_network
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    networks:
      - app_network
    ports:
      - '3000:3000'
    depends_on:
      - api
    
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    networks:
      - app_network
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    
networks:
  app_network:
    external: false

volumes:
  postgres_data:
